# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Baptiste/Documents/ENSEA/3D/S10_007_Soc/003_TP2/Zybo-soc-dossier6/seance_4/seance_4.srcs/sources_1/bd/zybo_7/ip/zybo_7_xbar_0/zybo_7_xbar_0.xci
# IP: The module: 'zybo_7_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Baptiste/Documents/ENSEA/3D/S10_007_Soc/003_TP2/Zybo-soc-dossier6/seance_4/seance_4.srcs/sources_1/bd/zybo_7/ip/zybo_7_xbar_0/zybo_7_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_7_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Baptiste/Documents/ENSEA/3D/S10_007_Soc/003_TP2/Zybo-soc-dossier6/seance_4/seance_4.srcs/sources_1/bd/zybo_7/ip/zybo_7_xbar_0/zybo_7_xbar_0.xci
# IP: The module: 'zybo_7_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Baptiste/Documents/ENSEA/3D/S10_007_Soc/003_TP2/Zybo-soc-dossier6/seance_4/seance_4.srcs/sources_1/bd/zybo_7/ip/zybo_7_xbar_0/zybo_7_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_7_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
