# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zybo_7/zybo_7.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_7 || ORIG_REF_NAME==zybo_7} -quiet] -quiet

# IP: bd/zybo_7/ip/zybo_7_processing_system7_0_0/zybo_7_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_7_processing_system7_0_0 || ORIG_REF_NAME==zybo_7_processing_system7_0_0} -quiet] -quiet

# IP: bd/zybo_7/ip/zybo_7_macc_ip_0_0/zybo_7_macc_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_7_macc_ip_0_0 || ORIG_REF_NAME==zybo_7_macc_ip_0_0} -quiet] -quiet

# IP: bd/zybo_7/ip/zybo_7_ps7_0_axi_periph_0/zybo_7_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_7_ps7_0_axi_periph_0 || ORIG_REF_NAME==zybo_7_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zybo_7/ip/zybo_7_rst_ps7_0_50M_0/zybo_7_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_7_rst_ps7_0_50M_0 || ORIG_REF_NAME==zybo_7_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/zybo_7/ip/zybo_7_xbar_0/zybo_7_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_7_xbar_0 || ORIG_REF_NAME==zybo_7_xbar_0} -quiet] -quiet

# IP: bd/zybo_7/ip/zybo_7_axi_timer_0_0/zybo_7_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_7_axi_timer_0_0 || ORIG_REF_NAME==zybo_7_axi_timer_0_0} -quiet] -quiet

# IP: bd/zybo_7/ip/zybo_7_auto_pc_0/zybo_7_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_7_auto_pc_0 || ORIG_REF_NAME==zybo_7_auto_pc_0} -quiet] -quiet

# XDC: bd/zybo_7/zybo_7_ooc.xdc
